### ISSUE TITLE
draw-cache: performance issues with threading/locking?

### ISSUE THREAD

**Issue by icefoxen** [alexheretic/glyph-brush#125]
Hey, this is some upstream research related to https://github.com/ggez/ggez/issues/867 .  Basically on some platforms text rendering performance appears to be rather lower than expected, and some (primitive) profiling makes it look like it spends about 30% of its time in crossbeam.  `glyph_brush` is the only user of crossbeam in that program, so, any idea what could be causing this problem?

**Comment by alexheretic** [comment]
Crossbeam is used in the draw-cache. If you're seeing a lot of activity there the draw cache is having to rasterize glyphs a lot. 

There is a edge case "thrashing". Every frame a new queue of text comes in that can't fit inside the texture additionally to what is already there. In this case the texture is cleared and we retry. If that succeeds but happens every frame the performance is bad & the draw-cache can't really do it's job.

Thrashing can be caused by misusing the API. If your text isn't being randomly changed every process-queued-frame I don't think it can happen.

You can also try increasing the initial cache texture size `.initial_cache_size((1024, 1024))`. In some cases this will allow all the multiple `process_queued` calls to fit into the texture. 

I'd like to maybe add thrash detection that automatically increases the texture size, however the API just isn't designed for single cache, multiple draws. If you need that you'll see much better performance from using a separate `GlyphBrush` per draw pipeline in a frame, so that each one only calls `process_queued` once per frame.

Cache behaviour is documented here: https://docs.rs/glyph_brush/0.7.1/glyph_brush/struct.GlyphBrush.html#caching-behaviour perhaps this, and the API itself, can be improved and clarified further.

**Comment by alexheretic** [comment]
I've been looking at this a little closer. It looks like the ggez text example is hitting the draw-cache with lots of randomly sized small text. It isn't causing thrashing, as I jumped to earlier. But it is, say, only around 16 small glyphs constantly changing and it looks like the overhead of multithreading is quite poor for this case.

This only happens for cache-misses (which shouldn't be happening nearly as much in real usage). Currently the draw-cache will use rayon/crossbeam to multithread outlining & rasterization whenever we have more than 1 new glyph to cache.

A couple of conclusions
* _glyph_brush_ should allow disabling the multithreading like _glyph_brush_draw_cache_ [already allows](https://docs.rs/glyph_brush_draw_cache/0.1.3/glyph_brush_draw_cache/struct.DrawCacheBuilder.html#method.multithread). I'm not sure why this wasn't there, probably just an oversight.
* The draw-cache should be a little more clever deciding to use multithreading. 1000 large glyphs absolutely multithread, 3 small glyphs don't bother. I'm not sure exactly what should happen in between though. Some testing will need to be done there.

**Comment by icefoxen** [comment]
I mean, IMO libraries shouldn't spawn threads at all unless that's what they're there for, but it's not my lib, so.  Thank you for the config option!  I'll try it out and see if it helps.

**Comment by icefoxen** [comment]
Text example mentioned above, using `multithread(false)` from the current git master, on some random computer (Linux+Intel+NVidia): went from ~50% CPU usage to ~15%.  So the threading overhead might not be the only thing going on with this, but it's certainly a factor.  Thank you!

**Comment by alexheretic** [comment]
#127 should be the best of both worlds, multithreading but only when there's a large enough queue of large enough glyphs to draw.

**Comment by alexheretic** [comment]
I've just published the improvements, cheers.

**Comment by icefoxen** [comment]
Tested and it works fantastic.  Thank you!
