### ISSUE TITLE
Documentation is unclear; I cannot get the crate to work.

### ISSUE THREAD

**Issue by KubaP** [alexheretic/glyph-brush#135]
I'll preface this by saying that *I* could be doing something wrong, but I've approached this just like any other crate; include it, build it, and then try to get an example working.

This is the point I've gotten stuck at, loading a font: [line 65 of example](https://github.com/alexheretic/glyph-brush/blob/master/glyph-brush/examples/opengl.rs#L65).

I've written the following:
```rust
let typeface = FontRef::try_from_slice(include_bytes!(r#"C:\Users\Kuba\Desktop\FiraCode-Regular.ttf"#)).expect("a font");
let mut glyph_brush = GlyphBrushBuilder::using_font(typeface).build();
```
And I get the following error:
```
error[E0282]: type annotations needed for `GlyphBrush<V, X, glyph_brush::ab_glyph::FontRef<'_>>`
   --> src\main.rs:236:64
    |
236 |     let mut glyph_brush = GlyphBrushBuilder::using_font(typeface).build();
    |         ---------------                                           ^^^^^ cannot infer type for type parameter `V` declared on the associated function `build`
    |         |
    |         consider giving `glyph_brush` the explicit type `GlyphBrush<V, X, glyph_brush::ab_glyph::FontRef<'_>>`, where the type parameter `V` is specified
```
That example doesn't include any type annotations at all. I have looked through the docs, and for the life of me I cannot figure out the type annotation required. There are no examples aside from this one.

I've managed to get something to compile by using a `FontArc` instead of a `FontRef`, and type annotating `GlyphBrush<GlyphVertex>` but that isn't what the example is showing. What's going wrong?

**Comment by alexheretic** [comment]
Thanks for raising an issue. The problem here is the vertex type `V` cannot be inferred by the compiler in your usage. This type is generic to accommodate generating & caching any kind of vertex data.

This works in the examples because rustc can infer the vertex type from the [`process_queued`](https://docs.rs/glyph_brush/0.7.2/glyph_brush/struct.GlyphBrush.html#method.process_queued) call, as this includes a vertex generator function. 

(This is similar to `let mut vec = Vec::new();` not working until you add a `vec.push(123_u32);` line to inform rustc the generic type.)

`GlyphBrush` has 4 generic types, which is a lot. It's more complex than I'd like but it's grown this way so as to be a more flexible tool. 

The most direct fix for you would to be provide the vertex & "extra" types to the builder that cannot be inferred.
```rust
type Vertex = (); // todo

let mut glyph_brush = GlyphBrushBuilder::using_font(typeface).build::<Vertex, Extra>();
```

It sounds like we can improve the documentation of these generic types, do you think this would help?

**Comment by alexheretic** [comment]
How about #136?

I've added documentation for each of the generic types & provided the above workaround in the previously sparse `GlyphBrushBuilder::build` docs.

**Comment by alexheretic** [comment]
That's fair. Having a low-level opengl example has proved useful and fairly easy to maintain, however there is a lot of complexity there. I'd be happy to accept doc improvements there or anywhere else.

**Comment by KubaP** [comment]
No, definitely. I'll submit some improvements at some point; once I've figured out how to translate that example into my own codebase/opengl abstraction and fully understood what's going on. Turns out font rendering is pretty complex huh.
