### ISSUE TITLE
Support providing your own shaders

### ISSUE THREAD

**Issue by icefoxen** [alexheretic/glyph-brush#40]
I'm trying to get ggez working on OpenGL ES 3.0, and a sticking point is that it doesn't support GLSL 1.50 shaders.  You have to provide GLSL ES 3.0 specifically.

`gfx_glyph` doesn't have a way to do this currently, it hardwires the shaders in.  However, it looks like that should be easy to fix, just by adding some extra methods to `GlyphBrushBuilder`.  If you agree I'll happily make a PR for it.

**Comment by alexheretic** [comment]
I'm not sure about the user supplying the actual shader strings. Do you
think we could add a simple enum selection of shader implementation? We may
even be able to detect which one is best to use automatically.

**Comment by icefoxen** [comment]
If the user supplies actual shader strings its up to them to supply the right one, instead of you having to write shaders for every imaginable version of OpenGL. I'm lazy, so I prefer that; up to you the approach you want to take though.

An enum giving the version you want to use is a not-unreasonable option though, I'll happily help add that too if you decide to go that route. It is just maybe a bit more work cause iirc auto-detection will rely on the window provider (glutin, SDL2, glfw) as well.

**Comment by alexheretic** [comment]
The issue is it opens up lots of ways for changes to break usage, currently I can switch up my pipeline ie use instancing without breaking usage.

Instead if it's simply adding two new ES shaders, we can add opt-in support for ES over the default glsl-150. Instead of looking to support every version, we just support a small amount of decent ones (like the GL support). Would that suffice do you think?

Also since I split the lib into glyph-brush this can be used to switch to a totally different pipeline with all the caching goodness.

**Comment by icefoxen** [comment]
Yeah, that's the joy of adding hooks but leaving implementation to your users... They can target a given version and that's fine as long as your changes result in a new major version of the crate. That's also a restriction on how much you can change internally without making a major version change though.

I'm perfectly happy with just supporting ES 3.0, for my own purposes, it just isn't the most general solution. Whether you want to go for "support specific versions that cover most cases" vs. "support any version but make the user do some extra work" is a trade off that's up to you. It sorta depends on how fast the API is evolving.

Hopefully gfx-hal makes this decision easier in the long run, but it's not quite there yet, so we can't rely on it 100%. :-D

**Comment by alexheretic** [comment]
I think for now let add the ES 3.0 switch to get it working for you. We may never get any more gl variant requests before the next gfx hits anyway.

I'm more fine with `gfx-glyph` as an opinionated `glyph-brush` wrapper now, since the latter is available on it's own. Perhaps ggez switching to `glyph-brush` makes sense (but I don't know ggez enough to say for sure), `gfx-glyph` itself isn't a lot of code these days.

**Comment by icefoxen** [comment]
Thanks a lot! I haven't really kept up with recent changes though, do you have a quick overview or the difference between the various subcrates?

**Comment by alexheretic** [comment]
`glyph-brush` is what `gfx-glyph` was with the render-api bits cut away. See the full usage example in the readme at https://github.com/alexheretic/glyph-brush/tree/master/glyph-brush.

It produces vertex data, along with texture data for the caller to use with whatever render api. `glyph-brush` has all the cpu caching goodness that underpins this lib. It's chiefly a way my work on layout & texture caching can be useful for people that aren't using gfx.

`gfx-glyph` has become a example of wrapping `glyph-brush` for a particular render api / lib, ie `gfx-rs`. I also added a [`gl-rs` example](https://github.com/alexheretic/glyph-brush/blob/master/glyph-brush/examples/opengl.rs).

So for wrestling full control of your draws `glyph-brush` may be attractive, and engine folk like yourself might want that.

All this is why `gfx-glyph` can be a little more clean and rigid in design. But if we go back to the original point, I'm still fine with having a ES3 switch that swaps out the shaders, as long as the rest of the pipeline code is unaffected.

**Comment by icefoxen** [comment]
Ooooh. I might experiment with working glyph-brush directly into using ggez's rendering pipeline. Something I never knew we needed until you mentioned it!

**Comment by icefoxen** [comment]
Basically obsoleted by `glyph-brush`, which is quite nice to use.
