### ISSUE TITLE
Remove screen dimensions dependency

### ISSUE THREAD

**Issue by hecrj** [alexheretic/glyph-brush#63]
Hi! I made [`wgpu_glyph`] a couple days ago (I will gladly give you ownership of the crate/repo if you want!), which integrates this library with [`wgpu`] to use it in [`coffee`].

As far as I know, the screen dimensions provided in the `GlyphBrush::process_queued` method are only used to apply an orthographic transform when computing vertex coordinates.

I think this dependency could be removed by computing absolute vertex coordinates (independent of the screen dimensions). Then, crates like `gfx_glyph` could still ask for the screen dimensions in `GlyphBrush::draw_queued` and simply call `GlyphBrush::draw_queued_with_transform` (which would not ask for screen dimensions anymore) with an orthographic projection. I think it would also simplify the code quite a bit.

This approach has the advantage that vertices do not need to be recomputed when the screen dimensions change. The only thing that needs to change is the orthographic transform. It also makes  `GlyphBrush::draw_queued_with_transform` easier to use (and consistent with the overall API, which uses absolute coordinates), as you do not really have to account for the transformation that is currently being applied to vertices.

Would this approach have any downsides that I am missing? I could try to implement these changes and make a PR if you agree to it.

Finally, I would like to thank you for this amazing library :)

[`wgpu_glyph`]: https://github.com/hecrj/wgpu_glyph
[`wgpu`]: https://github.com/gfx-rs/wgpu
[`coffee`]: https://github.com/hecrj/coffee

**Comment by alexheretic** [comment]
The `glyph_brush` api allows you to use the screen dimensions to compute gl positions in the `to_vertex` function, and yes `gfx_glyph` uses that so the default transform is identity. It makes is simpler _in a way_.

But, I don't believe users of `glyph_brush` _have_ to do it this way. Simply ignore the screen dimensions in your `to_vertex` function as you please. In fact `glyph_brush` only takes screen dimensions in order to supply it to the `to_vertex` function, so you could just pass dummy dimension values to `glyph_brush`. 

Background/history: Pre-baked glyphs really don't transform very well at all. Only a limited set of transforms work well on the GPU, the text is really only meant to be viewed in a single pixel perfect alignment to pixels that matches their rasterization. Ie screen text. So the pre-baked rasterization sort of suits a matching pre-baked transform. I started `gfx_glyph` this way and only added the custom transform support later _(so I could do whole-pixel scrolling of text sections in Robo Instructus)_.

But I think your strategy sounds fine, in fact the more I think about it the more it sounds easier to do custom transforms your way. But I don't think `glyph_brush` will stop you doing it in `wgpu_glyph`.

**Comment by hecrj** [comment]
> But I don't think glyph_brush will stop you doing it in wgpu_glyph.

Yes, it does not stop me. But I tried to keep the API semantically similar to `gfx_glyph`, as I think users will expect that and I am currently using both in my engine (`wgpu` still does not support OpenGL). Also, in order to remove the screen dimensions dependency I would have to pass "dummy" dimension values to `process_queued`, which feels a bit hacky.

Additionally, in order to use transforms with `gfx_glyph` I will need to "undo" the baked transform with an inverse projection so I can actually offer an API that defines transformations in the same coordinate space that text positions are defined (which makes defining whole pixel transformations easier and decoupled from target size).

> Pre-baked glyphs really don't transform very well at all.

I understand, but the current API is not protecting against this. In fact, it is making it harder to pass the correct transform.
