### ISSUE TITLE
Make it possible to remove a font?

### ISSUE THREAD

**Issue by icefoxen** [alexheretic/glyph-brush#72]
Basically, there's no way to ever remove a font from the cache, which seems like an odd omission.  Generational indices might make this easy to do well?

Source: https://github.com/ggez/ggez/issues/644

**Comment by alexheretic** [comment]
I avoid such outward mutability when I can so that cache logic can stay simple. Actually having `add_font` an omission, if you like, but this is done without affecting the cache so why not.

I'd basically need to invalidate all caches if a font was removed. However, you can already do this by "simply" rebuilding the `GlyphBrush` without the undesired fonts. I think this way better reflects the performance characteristics too.

I guess it isn't trivial to recreate a `GlyphBrush` right now, you'd have to keep track of the builder settings & make sure to use the correct texture size after resizes.

I made a slicker way to do this with rusttype's `Cache`, where you can use a `to_builder()` method to get a correctly setup `CacheBuilder` and use that to `rebuild(&mut Cache)`. This is pretty ergonomic, but is also clear that the cache _is_ being rebuilt ie this isn't something that should be done often.

I wouldn't mind having a similar couple of methods in this crate, if that helps?

**Comment by alexheretic** [comment]
I implemented this because I can't really think about code without writing it... Let me know if the PR is helpful.

**Comment by icefoxen** [comment]
> I avoid such outward mutability when I can so that cache logic can stay simple.

I tooootally sympathize.  :grinning: 

Your approach of "make it easy to empty a the cache" is actually a pretty nice one, for my purposes.  A very useful compromise between "making this perfect will be tons of complexity for very little gain" and "sometimes you have to get something done even when it's not ideal"

That said, this honestly isn't a terribly high priority for me.  The ggez bug itself is now fixed with documentation, and emptying the glyph cache isn't terribly hard for ggez.  Since ggez free to be as opinionated as it wants about what the `GlyphBrushBuilder` includes, I don't think lack of these methods would be *that* much of a problem for me.  So, include them if they're something you will want, but not if they're just going to sit around being a maintenance burden.

**Comment by alexheretic** [comment]
Ok cool, I'll probably merge it a little later then as I think it'll be a useful ability, but it is breaking.
