### ISSUE TITLE
`glyph_bounds` returning incorrect values with Arial font

### ISSUE THREAD

**Issue by hecrj** [alexheretic/glyph-brush#87]
Hey, I have been using `GlyphBrush::glyph_bounds` nicely for a while (see #68). However, a user of `iced` just reported a weird case.

If I am not mistaken, this snippet should display the text in a single line:

```rust
let section = Section {
    text: "Eins Zwei Drei Vier Funf",
    scale: Scale::uniform(20.0),
    ..Section::default()
};

let bounds = glyph_brush.glyph_bounds(&section).unwrap();

glyph_brush.queue(Section {
    bounds: (bounds.width(), bounds.height()),
    ..section
});
```

However, when using the Arial font, the last word of the text is cut off:

![image](https://user-images.githubusercontent.com/518289/74597164-8660f000-505a-11ea-870c-6a0a346527dc.png)

The reported bounds are:

```
&bounds = Rect {
    min: Point {
        x: 0.0,
        y: 0.0,
    },
    max: Point {
        x: 192.67482,
        y: 20.0,
    },
}
```

At first, I thought it could be a precision issue, but even if I `ceil` the width to `193.0`, the issue still occurs. Any ideas what may be going on? I have only been able to reproduce the issue with the Arial font so far (__update:__ it seems to also happen with the OpenSans Light font). [Here is the full SSCCE](https://gist.github.com/hecrj/3f6c2aed1055ccd2ee634af372ed1e48).

**Comment by hecrj** [comment]
I think the cause is here:

https://github.com/alexheretic/glyph-brush/blob/fc1a24dc4bd222f65dba44392e8d852e71642433/glyph-brush-layout/src/lines.rs#L105-L107

On the last word, `caret.x + world.layout_width` is matching exactly the boundary returned by `glyph_bounds`. However, instead of its layout width, `word_max_x` is using the width of the bounds of the word, which is greater. `glyph_bounds` seems to not be taking this `word_max_x` into consideration.

I am also unsure of the purpose of the `ceil`.

Therefore, this change seems to fix this particular issue:

```rust
if progressed && caret.x + word.layout_width > self.width_bound {
```

But it probably breaks other stuff, right?

**Comment by alexheretic** [comment]
Thanks for raising this, I agree this should be consistent.

> ```rust
> if progressed && caret.x + word.layout_width > self.width_bound {
> ```
> But it probably breaks other stuff, right?

It will yes, but it's on the right lines. `word.bounds.map(|b| b.max.x).unwrap_or(word.layout_width)` was there to handle the trailing invisible glyph advance at the end of a word, typically a space.

There are two ways to think about a word's width, when normally laying out on a line we want to include the trailing space so that the next word is correctly positioned. But if the word is the last on the line we want to consider it's width without the trailing space, because if it fits on the line without the trailing space we're still good (and can forget about the space).

Consider for example `""Eins Zwei Drei Vier Funf "` _with a trailing space_.

The mistake I think was to use the pixel bounds as a way ignore the whitespace, in your example the pixel bounds are larger than the advance width, that possibility means this method is flawed.

I have a fix for this, that won't use pixel bounds at all but is trailing space aware. PR incoming.

**Comment by hecrj** [comment]
Whoa, I see. Thank you very much for the explanation!
